name: bebshar_poristhiti_stock
description: "With stock bebshar poristhiti"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3
  flutter_native_splash: ^2.4.2
  intl: ^0.19.0
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  pdf: ^3.11.1
  image: ^4.3.0
  path_provider: ^2.1.4
  open_file: ^3.5.9
  flutter_font_picker: ^1.4.0
  firebase_messaging: ^15.1.3
  logger: ^2.4.0
  flutter_local_notifications: ^18.0.1
  path: ^1.9.0
  excel: ^4.0.6
  file_picker: ^8.1.3
  table_calendar: ^3.1.2
  flutter_image_compress: ^2.3.0
  http: ^1.2.2
  mobile_scanner: ^6.0.2
  local_auth: ^2.3.0
  flutter_html_to_pdf: ^0.7.0
  permission_handler: ^11.3.1
  connectivity_plus: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/error.jpg
    - assets/image1.jpg
    - assets/image2.jpg
    - assets/image3.jpg
    - assets/image4.jpg
    - assets/placeholder.png
    - assets/login_pic.jpg
    - assets/icon/ic_launcher.png
    - assets/icon/app_icon_foreground.png
    - assets/icon/analytics_2518147.png
    - assets/icon/book_8998090.png
    - assets/icon/logistic-distribution_14669990.png
    - assets/icon/wallet_1747291.png
    - assets/icon/employee.png
    - assets/icon/due.png
    - assets/sell.png
    - assets/sandii.png
    - assets/watermark.png
    - assets/logo.png
    - assets/fonts/SolaimanLipi.ttf
  fonts:
    - family: SolaimanLipi
      fonts:
        - asset: assets/fonts/SolaimanLipi.ttf

flutter_launcher_icons:
  android: true
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"
  adaptive_icon_background: "#FFFF00"
  min_sdk_android: 21
  image_path: "assets/icon/app_icon_foreground.png"
  default_icon:
    android_insets: false

flutter_native_splash:
  color: "#87CEEB" # Background color
  image: assets/icon/ic_launcher.png # Your splash image
  android: true # Use boolean instead of a map
  ios: true # Optional, for iOS
  fullscreen: true # Fullscreen for both Android and iOS

